# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'My Hospital Management System',
    'version': '1.1',
    'summary': 'Hospital Management',
    'sequence': 1,
    'description': """
    """,
    'category': 'Productivity',
    'website': 'https://www.odoo.com',
    'images': [],
    'depends': ['base', 'hr', 'calendar', 'sale', 'sale_management', 'account', 'stock', 'board', 'sale_stock'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/sequence.xml',
        'data/mail_template.xml',
        'views/my_patient_view.xml',
        'views/my_doctor_view.xml',
        'views/my_appointment_view.xml',
        'views/appointment.xml',
        'views/my_hospitalization_view.xml',
        'views/hospitalization_view.xml',
        'views/my_inpatient_view.xml',
        'views/my_hospital_pharmacy_view.xml',
        'views/my_lab_management_view.xml',
        # 'views/my_invoicing_view.xml',
        'views/my_prescription_view.xml',
        'views/website_appointment.xml',
        'views/website_appointment_records.xml',
        'views/website_labtest.xml',
        'views/website_prescription.xml',
        'views/website_lab_report.xml',
        'views/dashboard.xml',
        'views/settings.xml',
        'reports/lab_report.xml',
        'reports/patient_report.xml',
        'reports/patient_prescription_report.xml',
        'reports/patient_medical_report.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'assets': {
        'web._assets_primary_variables': [],
        'web.assets_backend': [],
        'web.assets_frontend': [],
        'web.assets_tests': [],
        'web.qunit_suite_tests': [],
        'web.assets_qweb': [],
    },
    'license': 'LGPL-3',
}
