from . import my_patient
from . import my_doctor
from . import my_appointment
from . import appointment
from . import my_hospitalization
from . import hospitalization
from . import my_outpatient
from . import my_prescription
from . import my_prescription_line
from . import my_lab_management
from . import my_invoicing
from . import my_pharmacy
from . import purchase_add
from . import sale_add
from . import test_name
from . import lab_report
from . import patient_symptoms
from . import disease_name
from . import disease_report
from . import my_vaccination
from . import my_medication_line

